### ISSUE TITLE
Could not find a matching version of package crt79/sportmonks-football-api

### ISSUE THREAD

**Issue by kashmiry** [tetzilla/sportmonks-football-api#1]
Hello,
When I tried to run `composer require pyaesoneaung/sportmonks-football-api`
I get this error in the command line:

```
[InvalidArgumentException]                                                   
Could not find a matching version of package crt79/sportmonks-football-api.
Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

**Comment by kashmiry** [comment]
I understand now that I should run:
`composer require tetzilla/sportmonks-football-api:dev-master`
to be able to get the package.

**Comment by tetzilla** [comment]
I had some problems with packagist and composer because of my repository name. This was changed from crt79 to tetzilla. 

As you have noticed yourself:

`composer require tetzilla/sportmonks-football-api:dev-master`

works.
